import { expect, test } from '@playwright/test'

test('multi-resource inspection survives reload and ties CODE and AI to the same run', async ({page}, testInfo) => {
  test.setTimeout(120_000)
  await page.setViewportSize({width:1440,height:1000})
  const authRequests: string[] = []
  page.on('request', request => { if (request.url().includes('/api/v1/auth/')) authRequests.push(request.url()) })
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'租户区智能巡检'})).toBeVisible()
  expect(authRequests).toEqual([])
  const env = (await (await page.request.get('/api/v1/environments')).json()).items.find((row:{slug:string}) => row.slug === 'e2e')
  expect(env).toBeTruthy()
  await page.goto(`/?environment=${env.id}`)
  let triggerCount = 0
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/inspection-runs/trigger')) triggerCount += 1 })
  await page.getByRole('button',{name:'立即巡检',exact:true}).click()
  const drawer = page.getByRole('dialog')
  await expect(drawer).toContainText('E2E 环境 · e2e')
  await drawer.getByRole('button',{name:/控制面/}).click()
  await drawer.getByRole('button',{name:/LLM/}).click()
  const created = page.waitForResponse(response => response.url().endsWith('/inspection-runs/trigger') && response.request().method() === 'POST')
  await drawer.getByRole('button',{name:'开始巡检',exact:true}).click()
  const run = await (await created).json()
  await expect(drawer).toContainText(run.id)
  await page.reload()
  await page.getByRole('button',{name:/查看正在进行的巡检|查看巡检完成摘要/}).click()
  await expect(drawer).toContainText(run.id)
  await expect(drawer.getByText('AI 准入评估')).toHaveCount(0)
  await expect(drawer.getByText('执行代码插件')).toBeVisible()
  await expect(drawer.getByRole('button',{name:/查看本次巡检结果/})).toBeVisible({timeout:90_000})
  expect(triggerCount).toBe(1)
  await expect(drawer.getByRole('button',{name:'查看规则库',exact:true})).toBeVisible()
  await drawer.getByRole('button',{name:/查看本次巡检结果/}).click()
  await expect(page).toHaveURL(new RegExp(`/inspection-runs/${run.id}`))
  await expect(page.getByRole('heading',{name:'本次巡检结果',level:2})).toBeVisible()
  const resultUrl = `/api/v1/inspection-runs/${run.id}/result?environment_id=${env.id}`
  const before = await (await page.request.get(resultUrl)).json()
  expect(before.code_plugins).toHaveLength(3)
  const table = page.getByRole('region',{name:'本轮检查'})
  await expect(table.getByText('CODE',{exact:true})).toHaveCount(before.check_results.length)
  await expect(table.getByText('v1.0.0',{exact:true})).toHaveCount(before.check_results.length)
  await expect(page.getByRole('region',{name:'AI 巡检助手'})).toContainText('AI 不参与上面的 PASS / FAIL 判定')
  await page.screenshot({path:testInfo.outputPath('inspection-result.png'),fullPage:true})
  await page.reload()
  await expect(page.getByRole('heading',{name:'本次巡检结果',level:2})).toBeVisible()
  await page.getByRole('link',{name:'← 返回总览'}).click()
  await expect(page.getByRole('complementary',{name:'最近完成的巡检'})).toContainText(run.id.slice(0,8))
  await page.getByRole('textbox',{name:'向 AI 巡检助手提问'}).fill('哪些是代码分析？')
  const asked = page.waitForResponse(response => response.url().endsWith('/dashboard/ask'))
  await page.getByRole('button',{name:'发送问题'}).click()
  const answer = await (await asked).json()
  expect(answer.inspection_run_id).toBe(run.id)
  expect(answer.source.type).toBe('AI')
  expect(answer.references.some((ref:{source:string}) => ref.source === 'CODE')).toBe(true)
  await expect(page.locator('.dashboard-ai-answer')).toContainText('llm.ttft_slo')
  const after = await (await page.request.get(resultUrl)).json()
  expect(after.check_results).toEqual(before.check_results)
  expect(after.risks).toEqual(before.risks)
  await page.screenshot({path:testInfo.outputPath('dashboard.png'),fullPage:true})
  await page.getByRole('link',{name:'规则库',exact:true}).click()
  await expect(page.locator('.plugin-card')).toHaveCount(3)
  await expect(page.getByText('evaluate',{exact:true})).toHaveCount(3)
  await page.reload()
  await expect(page.locator('.plugin-card')).toHaveCount(3)
  await page.screenshot({path:testInfo.outputPath('rules.png'),fullPage:true})
  await page.setViewportSize({width:390,height:844})
  await expect(page.getByRole('heading',{name:'规则库',level:2})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button',{name:'打开主导航',exact:true}).click()
  await page.getByRole('link',{name:'总览',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'向 AI 巡检助手提问'})).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path:testInfo.outputPath('dashboard-mobile.png'),fullPage:true})
})
