# Generated by Django 4.2.16 on 2026-08-22 21:39

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeizationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_capability_id', models.CharField(db_index=True, max_length=192)),
                ('task_type', models.CharField(choices=[('RULE', 'Rule'), ('PLUGIN', 'Plugin'), ('NEW_DATA', 'New data')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('CODE_PENDING', 'Code pending'), ('DEVELOPING', 'Developing'), ('SHADOW', 'Shadow'), ('CODE_ACTIVE', 'Code active'), ('REJECTED', 'Rejected')], db_index=True, default='CODE_PENDING', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('target_claim', models.CharField(db_index=True, max_length=192)),
                ('implementation_type', models.CharField(choices=[('RULE', 'Rule'), ('EXEC', 'Exec'), ('REST', 'REST'), ('MCP', 'MCP')], max_length=16)),
                ('specification', models.JSONField(default=dict)),
                ('owner', models.CharField(default='', max_length=128)),
                ('historical_support', models.IntegerField(default=0)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('critical_false_positive', models.IntegerField(default=0)),
                ('shadow_cases', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'codeization_tasks',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_key', models.CharField(max_length=192, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('DISCOVERED', 'Discovered'), ('CONFIRMED', 'Confirmed'), ('RULE_CANDIDATE', 'Rule candidate'), ('CODE_PENDING', 'Code pending'), ('SHADOW', 'Shadow'), ('CODE_ACTIVE', 'Code active'), ('REJECTED', 'Rejected'), ('RETIRED', 'Retired')], db_index=True, default='DISCOVERED', max_length=32)),
                ('source_type', models.CharField(choices=[('INVESTIGATION', 'Investigation'), ('FEEDBACK', 'Feedback'), ('LEARNING_EVENT', 'Learning event')], db_index=True, max_length=32)),
                ('hypothesis', models.TextField(default='')),
                ('conclusion', models.TextField()),
                ('applicable_scope', models.JSONField(default=dict)),
                ('trigger_conditions', models.JSONField(default=list)),
                ('required_evidence', models.JSONField(default=list)),
                ('tool_sequence', models.JSONField(default=list)),
                ('human_summary', models.TextField(default='')),
                ('support_count', models.IntegerField(default=0)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('code_status', models.CharField(choices=[('CODE_ACTIVE', 'Code active'), ('PARTIAL_CODE', 'Partial code'), ('CODE_PENDING', 'Code pending'), ('SHADOW', 'Shadow'), ('NOT_CODED', 'Not coded')], db_index=True, default='NOT_CODED', max_length=32)),
                ('target_claim', models.CharField(db_index=True, default='', max_length=192)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'experiences',
            },
        ),
        migrations.CreateModel(
            name='ExperienceEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relation', models.CharField(choices=[('SUPPORT', 'Support'), ('COUNTEREXAMPLE', 'Counterexample'), ('CONTEXT', 'Context')], db_index=True, default='SUPPORT', max_length=32)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'db_table': 'experience_evidence',
            },
        ),
    ]
