# Generated by Django 4.2.16 on 2026-08-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('learning', '0001_initial'),
        ('risks', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceevidence',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.evidence'),
        ),
        migrations.AddField(
            model_name='experienceevidence',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.experience'),
        ),
        migrations.AddField(
            model_name='experience',
            name='source_investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='experience',
            name='source_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
        migrations.AddField(
            model_name='codeizationtask',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.experience'),
        ),
        migrations.AddField(
            model_name='codeizationtask',
            name='inspection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitem'),
        ),
        migrations.AddConstraint(
            model_name='experienceevidence',
            constraint=models.UniqueConstraint(fields=('experience', 'evidence', 'relation'), name='experience_evidence_relation_unique'),
        ),
    ]
