# Generated by Django 4.2.16 on 2026-08-22 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=64, unique=True)),
                ('environment_type', models.CharField(choices=[('DEV', 'Development'), ('TEST', 'Test'), ('PROD_SIM', 'Production simulation')], db_index=True, default='DEV', max_length=32)),
                ('tenant_key', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'environments',
            },
        ),
    ]
