# Generated by Django 4.2.16 on 2026-08-22 21:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('assets', '0001_initial'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_key', models.CharField(db_index=True, max_length=192)),
                ('fingerprint', models.CharField(max_length=128)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('domain', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], db_index=True, max_length=8)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('MITIGATING', 'Mitigating'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed'), ('INVALID', 'Invalid')], db_index=True, default='NEW', max_length=32)),
                ('current_conclusion', models.TextField(default='')),
                ('impact_summary', models.TextField(default='')),
                ('recommendation', models.TextField(default='')),
                ('first_seen_at', models.DateTimeField(db_index=True)),
                ('last_seen_at', models.DateTimeField(db_index=True)),
                ('recovered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('duration_days', models.IntegerField(default=1)),
                ('llm_involved_last', models.BooleanField(db_index=True, default=False)),
                ('current_investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investigations.investigation')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitem')),
                ('primary_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
            ],
            options={
                'db_table': 'risks',
            },
        ),
        migrations.CreateModel(
            name='RiskStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('MITIGATING', 'Mitigating'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed'), ('INVALID', 'Invalid')], max_length=32, null=True)),
                ('to_status', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('MITIGATING', 'Mitigating'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed'), ('INVALID', 'Invalid')], db_index=True, max_length=32)),
                ('reason', models.TextField(default='')),
                ('source', models.CharField(choices=[('SYSTEM', 'System'), ('HUMAN', 'Human'), ('REVERIFY', 'Reverify')], db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectionrun')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'db_table': 'risk_status_history',
            },
        ),
        migrations.CreateModel(
            name='RiskObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('detected', models.BooleanField(db_index=True, default=True)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], max_length=8)),
                ('status_after', models.CharField(choices=[('NEW', 'New'), ('ACTIVE', 'Active'), ('ACKNOWLEDGED', 'Acknowledged'), ('MITIGATING', 'Mitigating'), ('RECOVERED', 'Recovered'), ('CLOSED', 'Closed'), ('INVALID', 'Invalid')], max_length=32)),
                ('finding_count', models.IntegerField(default=0)),
                ('evidence_count', models.IntegerField(default=0)),
                ('snapshot', models.JSONField(default=dict)),
                ('inspection_item_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitemrun')),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionrun')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risks.risk')),
            ],
            options={
                'db_table': 'risk_observations',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('METRIC', 'Metric'), ('LOG', 'Log'), ('EVENT', 'Event'), ('TOPOLOGY', 'Topology'), ('TOOL_RESULT', 'Tool result'), ('CHANGE', 'Change')], db_index=True, max_length=32)),
                ('evidence_key', models.CharField(db_index=True, max_length=192)),
                ('summary', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('source', models.CharField(db_index=True, max_length=128)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('materiality', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('raw_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('inspection_item_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectionitemrun')),
                ('inspection_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectionrun')),
                ('investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigation')),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk')),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='riskobservation',
            constraint=models.UniqueConstraint(fields=('risk', 'inspection_run'), name='risk_observation_risk_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='risk',
            constraint=models.UniqueConstraint(fields=('environment', 'fingerprint'), name='risk_environment_fingerprint_unique'),
        ),
    ]
