# Generated by Django 4.2.16 on 2026-08-22 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(db_index=True, max_length=192)),
                ('domain', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(default='')),
                ('execution_mode', models.CharField(choices=[('CODE_ONLY', 'Code only'), ('CODE_FIRST_AI_FALLBACK', 'Code first, AI fallback'), ('AI_INVESTIGATION', 'AI investigation'), ('LEARNING_MODE', 'Learning mode')], db_index=True, max_length=40)),
                ('code_status', models.CharField(choices=[('CODE_ACTIVE', 'Code active'), ('PARTIAL_CODE', 'Partial code'), ('CODE_PENDING', 'Code pending'), ('SHADOW', 'Shadow'), ('NOT_CODED', 'Not coded')], db_index=True, max_length=32)),
                ('code_coverage_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], default='P3', max_length=8)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('schedule_policy', models.JSONField(default=dict)),
                ('required_claims', models.JSONField(default=list)),
                ('resolved_claims', models.JSONField(default=list)),
                ('llm_responsibilities', models.JSONField(default=list)),
                ('version', models.CharField(default='1.0.0', max_length=32, validators=[django.core.validators.RegexValidator(message='Use a numeric semantic version in x.x.x format.', regex='^\\d+\\.\\d+\\.\\d+$')])),
            ],
            options={
                'db_table': 'inspection_items',
            },
        ),
        migrations.CreateModel(
            name='MockDataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seed', models.BigIntegerField(db_index=True)),
                ('scenario', models.CharField(db_index=True, max_length=64)),
                ('dataset_date', models.DateField(db_index=True)),
                ('version', models.CharField(default='1.0.0', max_length=32, validators=[django.core.validators.RegexValidator(message='Use a numeric semantic version in x.x.x format.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('status', models.CharField(choices=[('GENERATING', 'Generating'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='GENERATING', max_length=32)),
                ('generator_config', models.JSONField(default=dict)),
                ('asset_count', models.IntegerField(default=0)),
                ('metric_count', models.IntegerField(default=0)),
                ('log_count', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('change_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
            ],
            options={
                'db_table': 'mock_datasets',
            },
        ),
        migrations.CreateModel(
            name='MockLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=16)),
                ('message', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.mockdataset')),
            ],
            options={
                'db_table': 'mock_logs',
            },
        ),
        migrations.CreateModel(
            name='MockEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(default='', max_length=128)),
                ('message', models.TextField(default='')),
                ('attributes', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.mockdataset')),
            ],
            options={
                'db_table': 'mock_events',
            },
        ),
        migrations.CreateModel(
            name='MockChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('change_type', models.CharField(db_index=True, max_length=64)),
                ('summary', models.TextField()),
                ('attributes', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.mockdataset')),
            ],
            options={
                'db_table': 'mock_changes',
            },
        ),
        migrations.CreateModel(
            name='InspectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_date', models.DateField(db_index=True)),
                ('trigger_type', models.CharField(choices=[('AIRFLOW', 'Airflow'), ('MANUAL', 'Manual'), ('API', 'API')], db_index=True, max_length=32)),
                ('airflow_dag_run_id', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_items', models.IntegerField(default=0)),
                ('success_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('risk_count', models.IntegerField(default=0)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.mockdataset')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
            ],
            options={
                'db_table': 'inspection_runs',
            },
        ),
        migrations.CreateModel(
            name='InspectionItemRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=32)),
                ('ai_admission_status', models.CharField(choices=[('NOT_EVALUATED', 'Not evaluated'), ('NO_AI', 'No AI'), ('AI_ELIGIBLE', 'AI eligible'), ('AI_DEFERRED', 'AI deferred'), ('DATA_INVALID', 'Data invalid')], db_index=True, default='NOT_EVALUATED', max_length=40)),
                ('asset_scope', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('model_provider', models.CharField(blank=True, max_length=32, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitem')),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionrun')),
            ],
            options={
                'db_table': 'inspection_item_runs',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finding_code', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(max_length=192)),
                ('category', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4')], db_index=True, default='P3', max_length=8)),
                ('materiality', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved'), ('INVALID', 'Invalid')], db_index=True, default='ACTIVE', max_length=32)),
                ('value', models.JSONField(default=dict)),
                ('source_type', models.CharField(choices=[('METRIC', 'Metric'), ('LOG', 'Log'), ('EVENT', 'Event'), ('TOPOLOGY', 'Topology'), ('RULE', 'Rule')], db_index=True, max_length=32)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
                ('inspection_item_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitemrun')),
            ],
            options={
                'db_table': 'findings',
            },
        ),
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('snapshot_date', models.DateField()),
                ('assets_total', models.IntegerField(default=0)),
                ('assets_covered', models.IntegerField(default=0)),
                ('inspection_item_count', models.IntegerField(default=0)),
                ('risk_total', models.IntegerField(default=0)),
                ('p1_count', models.IntegerField(default=0)),
                ('p2_count', models.IntegerField(default=0)),
                ('new_count', models.IntegerField(default=0)),
                ('worsened_count', models.IntegerField(default=0)),
                ('recovered_count', models.IntegerField(default=0)),
                ('pending_action_count', models.IntegerField(default=0)),
                ('pending_reverify_count', models.IntegerField(default=0)),
                ('code_only_cases', models.IntegerField(default=0)),
                ('ai_dependent_cases', models.IntegerField(default=0)),
                ('code_coverage_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('deterministic_deflection_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('ai_displacement_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('data_completeness_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('summary', models.JSONField(default=dict)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
                ('inspection_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionrun')),
            ],
            options={
                'db_table': 'daily_snapshots',
            },
        ),
        migrations.CreateModel(
            name='MockMetric',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(db_index=True, max_length=128)),
                ('ts', models.DateTimeField(db_index=True)),
                ('value', models.FloatField()),
                ('labels', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.mockdataset')),
            ],
            options={
                'db_table': 'mock_metrics',
                'indexes': [models.Index(fields=['dataset', 'asset', 'metric_name', 'ts'], name='mock_metric_dataset_d81cf3_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionrun',
            constraint=models.UniqueConstraint(fields=('environment', 'run_date', 'trigger_type', 'airflow_dag_run_id'), name='inspection_run_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='inspectionitemrun',
            constraint=models.UniqueConstraint(fields=('inspection_run', 'inspection_item'), name='inspection_item_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='dailysnapshot',
            constraint=models.UniqueConstraint(fields=('environment', 'snapshot_date'), name='daily_snapshot_environment_date_unique'),
        ),
    ]
