# Generated by Django 4.2.16 on 2026-08-25 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspectionitem_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('asset_selector', models.JSONField(default=dict)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'resource_types',
            },
        ),
        migrations.CreateModel(
            name='InspectionItemResourceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_types', to='inspections.inspectionitem')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_items', to='inspections.resourcetype')),
            ],
            options={
                'db_table': 'inspection_item_resource_types',
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionitemresourcetype',
            constraint=models.UniqueConstraint(fields=('resource_type', 'inspection_item'), name='uq_resource_type_inspection_item'),
        ),
    ]
