# Generated by Django 4.2.16 on 2026-08-25 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_seed_resource_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionitemrun',
            name='inspection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_runs', to='inspections.inspectionitem'),
        ),
        migrations.AlterField(
            model_name='inspectionitemrun',
            name='inspection_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_runs', to='inspections.inspectionrun'),
        ),
    ]
