# Generated by Django 4.2.16 on 2026-08-25 07:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_alter_inspectionitemrun_inspection_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceInspectionSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assets_total', models.IntegerField(default=0)),
                ('assets_covered', models.IntegerField(default=0)),
                ('inspection_item_count', models.IntegerField(default=0)),
                ('success_item_count', models.IntegerField(default=0)),
                ('failed_item_count', models.IntegerField(default=0)),
                ('finding_count', models.IntegerField(default=0)),
                ('risk_count', models.IntegerField(default=0)),
                ('p1_count', models.IntegerField(default=0)),
                ('p2_count', models.IntegerField(default=0)),
                ('p3_count', models.IntegerField(default=0)),
                ('p4_count', models.IntegerField(default=0)),
                ('ai_dependent_cases', models.IntegerField(default=0)),
                ('ai_investigation_count', models.IntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(default=dict)),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_summaries', to='inspections.inspectionrun')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_summaries', to='inspections.resourcetype')),
            ],
            options={
                'db_table': 'resource_inspection_summaries',
            },
        ),
        migrations.AddConstraint(
            model_name='resourceinspectionsummary',
            constraint=models.UniqueConstraint(fields=('inspection_run', 'resource_type'), name='resource_summary_run_type_unique'),
        ),
    ]
