# Generated by Django 4.2.16 on 2026-08-25 07:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_resourceinspectionsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRunEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='INFO', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('inspection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='inspections.inspectionrun')),
            ],
            options={
                'db_table': 'inspection_run_events',
                'ordering': ['sequence', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionrunevent',
            constraint=models.UniqueConstraint(fields=('inspection_run', 'sequence'), name='inspection_run_event_sequence_unique'),
        ),
    ]
