# Generated by Django 4.2.16 on 2026-09-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_check_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionitem',
            name='rule_config',
            field=models.JSONField(default=dict),
        ),
    ]
