# Generated by Django 4.2.16 on 2026-08-22 21:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_id', models.CharField(max_length=192, unique=True)),
                ('name', models.CharField(db_index=True, max_length=192)),
                ('description', models.TextField(default='')),
                ('domain', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('RETIRED', 'Retired')], db_index=True, default='ACTIVE', max_length=32)),
                ('owner', models.CharField(default='platform', max_length=128)),
                ('read_only', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'capabilities',
            },
        ),
        migrations.CreateModel(
            name='CapabilityVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Use a numeric semantic version in x.x.x format.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('implementation_type', models.CharField(choices=[('RULE', 'Rule'), ('EXEC', 'Exec'), ('REST', 'REST'), ('MCP', 'MCP')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('CANDIDATE', 'Candidate'), ('SHADOW', 'Shadow'), ('ACTIVE', 'Active'), ('RETIRED', 'Retired')], db_index=True, default='CANDIDATE', max_length=32)),
                ('manifest', models.JSONField(default=dict)),
                ('semantic_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=192), default=list, size=None)),
                ('subjects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=192), default=list, size=None)),
                ('resolves', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=192), default=list, size=None)),
                ('input_schema', models.JSONField(default=dict)),
                ('output_schema', models.JSONField(default=dict)),
                ('endpoint', models.CharField(blank=True, max_length=512, null=True)),
                ('script_path', models.CharField(blank=True, max_length=512, null=True)),
                ('mcp_server', models.CharField(blank=True, max_length=192, null=True)),
                ('mcp_tool', models.CharField(blank=True, max_length=192, null=True)),
                ('timeout_seconds', models.IntegerField(default=15)),
                ('retry_count', models.IntegerField(default=0)),
                ('health_status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy')], db_index=True, default='UNKNOWN', max_length=32)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capability_versions',
            },
        ),
        migrations.CreateModel(
            name='InspectionCapabilityBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('DETECTOR', 'Detector'), ('ENRICHER', 'Enricher'), ('RESOLVER', 'Resolver'), ('VALIDATOR', 'Validator')], db_index=True, max_length=32)),
                ('claim', models.CharField(db_index=True, max_length=192)),
                ('priority', models.IntegerField(default=100)),
                ('required', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('capability_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capabilities.capabilityversion')),
            ],
            options={
                'db_table': 'inspection_capability_bindings',
            },
        ),
    ]
