# Generated by Django 4.2.16 on 2026-08-22 21:39

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('capabilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectioncapabilitybinding',
            name='inspection_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.inspectionitem'),
        ),
        migrations.AddField(
            model_name='capabilityversion',
            name='capability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capabilities.capability'),
        ),
        migrations.AddField(
            model_name='capability',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capabilities.capabilityversion'),
        ),
        migrations.AddConstraint(
            model_name='inspectioncapabilitybinding',
            constraint=models.UniqueConstraint(fields=('inspection_item', 'capability_version', 'role', 'claim'), name='inspection_capability_binding_unique'),
        ),
        migrations.AddIndex(
            model_name='capabilityversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['semantic_tags'], name='capability__semanti_a29644_gin'),
        ),
        migrations.AddIndex(
            model_name='capabilityversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['subjects'], name='capability__subject_3c189f_gin'),
        ),
        migrations.AddIndex(
            model_name='capabilityversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['resolves'], name='capability__resolve_295e94_gin'),
        ),
        migrations.AddConstraint(
            model_name='capabilityversion',
            constraint=models.UniqueConstraint(fields=('capability', 'version'), name='capability_version_unique'),
        ),
    ]
