# Generated by Django 4.2.16 on 2026-08-23 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capabilityversion',
            name='version',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Use a numeric semantic version in x.x.x format.', regex='\\A\\d+\\.\\d+\\.\\d+\\Z')]),
        ),
    ]
