# Generated by Django 4.2.16 on 2026-09-26 03:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=64)),
                ('sample_id', models.CharField(max_length=192)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField()),
                ('evaluation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hardware_snapshots', to='assets.asset')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'window_end'], name='idx_hw_asset_window')],
            },
        ),
        migrations.AddConstraint(
            model_name='hardwaresnapshot',
            constraint=models.UniqueConstraint(fields=('environment', 'source', 'sample_id'), name='uq_hw_env_source_sample'),
        ),
        migrations.AddConstraint(
            model_name='hardwaresnapshot',
            constraint=models.UniqueConstraint(fields=('asset', 'window_start', 'window_end'), name='uq_hw_asset_window'),
        ),
    ]
