# Generated by Django 4.2.16 on 2026-08-22 21:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_key', models.CharField(max_length=192)),
                ('asset_type', models.CharField(choices=[('CLUSTER', 'Cluster'), ('HOST', 'Host'), ('VM', 'VM'), ('POD', 'Pod'), ('GPU', 'GPU'), ('LLM_INSTANCE', 'LLM instance')], db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=192)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=32)),
                ('labels', models.JSONField(default=dict)),
                ('topology', models.JSONField(default=dict)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.asset')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('environment', 'external_key'), name='asset_environment_external_key_unique'),
        ),
    ]
