# Generated by Django 4.2.16 on 2026-08-22 21:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capabilities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_type', models.CharField(choices=[('RISK', 'Risk'), ('INSPECTION_ITEM', 'Inspection item'), ('INVESTIGATION', 'Investigation'), ('EXPERIENCE', 'Experience')], db_index=True, max_length=32)),
                ('context_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], db_index=True, default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System'), ('TOOL', 'Tool')], db_index=True, max_length=16)),
                ('content', models.TextField(default='')),
                ('structured_content', models.JSONField(default=dict)),
                ('model_provider', models.CharField(blank=True, max_length=32, null=True)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator(message='Use a numeric semantic version in x.x.x format.', regex='^\\d+\\.\\d+\\.\\d+$')])),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'conversation_messages',
            },
        ),
        migrations.CreateModel(
            name='HumanFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('HELPFUL', 'Helpful'), ('INCORRECT', 'Incorrect'), ('MISSING_EVIDENCE', 'Missing evidence'), ('WRONG_TOOL_PATH', 'Wrong tool path'), ('CONFIRMED_ROOT_CAUSE', 'Confirmed root cause'), ('FALSE_POSITIVE', 'False positive'), ('CUSTOM', 'Custom')], db_index=True, max_length=40)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(default='')),
                ('confirmed_conclusion', models.TextField(default='')),
                ('correction', models.JSONField(default=dict)),
                ('create_experience', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'human_feedback',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger_type', models.CharField(choices=[('HUMAN', 'Human'), ('AUTO', 'Automatic'), ('LEARNING', 'Learning')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('RUNNING', 'Running'), ('RESOLVED', 'Resolved'), ('UNRESOLVED', 'Unresolved'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='CREATED', max_length=32)),
                ('entry_reason', models.CharField(choices=[('CLAIM_GAP', 'Claim gap'), ('CONFLICT', 'Conflict'), ('TREND_GAP', 'Trend gap'), ('USER_QUESTION', 'User question'), ('LEARNING_EVENT', 'Learning event')], db_index=True, max_length=64)),
                ('missing_claim', models.CharField(blank=True, db_index=True, max_length=192, null=True)),
                ('model_provider', models.CharField(max_length=32)),
                ('model_name', models.CharField(max_length=128)),
                ('max_rounds', models.IntegerField(default=3)),
                ('rounds_used', models.IntegerField(default=0)),
                ('max_tool_calls', models.IntegerField(default=5)),
                ('tool_calls_used', models.IntegerField(default=0)),
                ('conclusion', models.TextField(default='')),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investigations',
            },
        ),
        migrations.CreateModel(
            name='InvestigationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('node_name', models.CharField(default='', max_length=64)),
                ('status', models.CharField(choices=[('INFO', 'Info'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INFO', max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'investigation_events',
            },
        ),
        migrations.CreateModel(
            name='ToolCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_id', models.CharField(max_length=128, unique=True)),
                ('tool_name', models.CharField(db_index=True, max_length=192)),
                ('input_args', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('result_summary', models.TextField(default='')),
                ('result_payload', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.conversationmessage')),
                ('capability_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capabilities.capabilityversion')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.conversation')),
            ],
            options={
                'db_table': 'tool_calls',
            },
        ),
    ]
