# Generated by Django 4.2.16 on 2026-08-22 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inspections', '0001_initial'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolcall',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.evidence'),
        ),
        migrations.AddField(
            model_name='toolcall',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='investigationevent',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='inspection_item_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inspections.inspectionitemrun'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.conversation'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.conversationmessage'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
        migrations.AddField(
            model_name='humanfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigations.conversation'),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.conversationmessage'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.environment'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='investigation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.investigation'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='risks.risk'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='investigationevent',
            constraint=models.UniqueConstraint(fields=('investigation', 'sequence'), name='investigation_event_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='humanfeedback',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='human_feedback_rating_between_one_and_five'),
        ),
    ]
