# Generated by Django 4.2.16 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigations", "0003_alter_conversationmessage_prompt_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigation",
            name="claim_heartbeat_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="investigation",
            name="claim_token",
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
