# Generated by Django 4.2.16 on 2026-08-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0004_investigation_claim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='context_type',
            field=models.CharField(choices=[('RISK', 'Risk'), ('INSPECTION_ITEM', 'Inspection item'), ('INVESTIGATION', 'Investigation'), ('EXPERIENCE', 'Experience'), ('RESOURCE_TYPE', 'Resource type'), ('RESOURCE_RUN', 'Resource run')], db_index=True, max_length=32),
        ),
    ]
